Fix incorrect links to source code in docs
pimcore/ecommerce-framework-bundle pull request #138
Opened 2023-11-10 11:14 UTC by GNi33

As the ecommerce framework has been moved into a standalone bundle, some links in the documentation which are still pointing to the main pimcore repository are broken

2023-11-10 12:39 UTC, mcassier31 requested changes
Hi! Thanks for your contribution!
Could you apply the following changes, please? :)

2023-11-10 12:39 UTC, mcassier31 commented on doc/09_Working_with_Prices/09_Calculate_with_Prices.md
> +Decimal
```suggestion
```

2023-11-10 12:39 UTC, mcassier31 commented on doc/09_Working_with_Prices/09_Calculate_with_Prices.md
> +../../
```suggestion
```

2023-11-10 12:39 UTC, mcassier31 commented on doc/10_Working_with_Availabilities.md
> +Currently, the framework ships only with a [sample implementation](https://github.com/pimcore/ecommerce-framework-bundle/blob/1.x/src/AvailabilitySystem/AvailabilitySystem.php#L20)
```suggestion
Currently, the framework ships only with a [sample implementation](https://github.com/pimcore/ecommerce-framework-bundle/blob/1.x/src/AvailabilitySystem/AvailabilitySystem.php#L21)
```

2023-11-10 14:03 UTC, mcassier31 commented
Thanks for the update! Could you also rebase to 1.0 (bugfix) please?

2023-11-16 10:27 UTC, GNi33 commented
I see, would I need to change the absolute links from `/pimcore/ecommerce-framework-bundle/blob/**1.x**/` to `/pimcore/ecommerce-framework-bundle/blob/**1.0**/` in that case?

2023-11-16 14:35 UTC, mcassier31 commented
Hi! As 1.0 will be deleted after the next minor release, keeping the links pointing to 1.x is better. In that way, we will not need to update them again for 1.1 :)

2023-12-15 10:41 UTC, merged