[Task]: Check usages of Pimcore\Db\Helper::insertOrUpdate and ON DUPLICATE KEY
pimcore/ecommerce-framework-bundle pull request #20
Opened 2023-04-04 12:41 UTC by mcop1

Resolves #19

2023-04-11 13:37 UTC, kingjia90 requested changes

2023-04-11 13:37 UTC, kingjia90 commented on src/IndexService/Worker/Helper/MySql.php
>          if (!Cache\RuntimeCache::isRegistered($cacheKey)) {
`$cache` doesn't seem in use, was meant?
```suggestion
        if (!Cache\RuntimeCache::isRegistered($cacheKey) || !$cache) {
```

but i don't get the changes in the core 
https://github.com/pimcore/pimcore/blob/230610923ee36ab370261fd13a84619be0162ad8/lib/Model/Dao/AbstractDao.php#L72
even though this class doens't extends that, doesn't need to have the same signature

2023-04-11 13:37 UTC, kingjia90 commented on src/IndexService/Worker/Helper/MySql.php
>              Cache\RuntimeCache::save($columns, $cacheKey);
```suggestion
            Cache\RuntimeCache::save($allColumns, $cacheKey);
```

2023-04-12 12:40 UTC, mattamon reviewed
Do we need this for the beta release of the bundle?

2023-04-12 12:54 UTC, kingjia90 commented
> Do we need this for the beta release of the bundle?

i would say so, the demo beta would be not working properly without ecommerce framework

2023-04-12 13:09 UTC, kingjia90 approved these changes

2023-04-12 15:16 UTC, merged