Set amount to the subtotal when the discount amount exceeds the subtotal
pimcore/ecommerce-framework-bundle pull request #200
Opened 2024-09-30 16:07 UTC by jan888adams

The cart discount reduces the total cart price, including modifications like shipping costs. This behavior differs from percentage discounts, which only apply to the subtotal and do not affect additional costs.

This is fixed by setting the discount amount to the subtotal when the discount amount exceeds the subtotal..

2024-09-30 18:20 UTC, jdreesen commented on src/PricingManager/Action/CartDiscount.php
> +        $amount = $amount->mul(-1);
Why this change?

2024-09-30 18:26 UTC, jan888adams commented on src/PricingManager/Action/CartDiscount.php
> +        $amount = $amount->mul(-1);
I didn't notice that

2024-10-01 14:44 UTC, fashxp commented
Not sure, if we should make that behavior configurable?
Or at least we merge that for the next minor and add a upgrade note to it - since it is a change in behavior that someone could use the way it is right now. 

WDYT?

2024-10-02 11:14 UTC, jan888adams commented
That sounds like a good idea. I would implement the current behavior as the default, with an option to switch to the new calculation. Additionally, I would apply the change only to the fixed amount and deprecate the old method of calculating cart discounts with fixed amounts.

2024-10-07 08:56 UTC, fashxp commented
please just update the english translation file. the rest is translated via poeditor, see also https://pimcore.com/docs/platform/Pimcore/Multi_Language_i18n/Admin_Translations/#adding-your-own-admin-languages-since-v636

2024-10-09 09:38 UTC, fashxp requested changes

2024-10-09 09:38 UTC, fashxp commented on src/PricingManager/Action/CartDiscount.php
> +        } else {
hmm, on second thought, I wouldn't deprecate the old way. As discussed, there might be use cases for that behavior too.

2024-10-09 12:32 UTC, jan888adams commented on src/PricingManager/Action/CartDiscount.php
> +        } else {
No problem at all, I'll make the change. I also suggest we allow percentage-based cart discounts to be selectable, so they can apply either to the total or the subtotal. Currently, it always applies to the subtotal, but since it’s not an easy change, I would leave it for now.

2024-10-10 06:16 UTC, fashxp commented on src/PricingManager/Action/CartDiscount.php
> +        } else {
thank you very much! 
I agree for leaving out the percentage-based cart discounts for now

2024-10-10 06:24 UTC, fashxp approved these changes

2024-10-10 06:26 UTC, fashxp commented
thanks again!

2024-10-10 06:26 UTC, merged